all:
	gcc ch4_24/thread_monte.c -o ch4_24/monte.out -pthread
	gcc ch4_27/thread_fib.c -o ch4_27/fib.out -pthread
	gcc ch6_33/problem_mutex.c -o ch6_33/mutex.out -pthread
	gcc ch6_33/problem_nomutex.c -o ch6_33/nomutex.out -pthread
clean:
	rm ch4_24/*.out
	rm ch4_27/*.out
	rm ch6_33/*.out