all:
	gcc ch7_15/fib.c -o ch7_15/fib.out -pthread
	gcc ch7_17/monte.c -o ch7_17/monte.out -pthread
	gcc ch8_32/bridge.c -o ch8_32/bridge.out -pthread
	gcc ch9_28/addresses.c -o ch9_28/addresses.out -pthread
clean:
	rm ch7_15/*.out
	rm ch7_17/*.out
	rm ch8_32/*.out
	rm ch9_28/*.out